/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pairs */
        get: operations["list_pairs_pairs_get"];
        put?: never;
        /** Create Pair */
        post: operations["create_pair_pairs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairs/{pair_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Pair */
        delete: operations["remove_pair_pairs__pair_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairs/{pair_id}/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candles */
        get: operations["get_candles_pairs__pair_id__candles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairs/{pair_id}/indicators/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Indicator
         * @description Return a (potentially multi-output) indicator series.
         *
         *     Per Decision 20: the ``name`` path param dispatches to a per-indicator
         *     params shape. SMA/EMA/RSI take ``period``; MACD takes ``fast``/``slow``/
         *     ``signal``; BB takes ``period``/``stddev``. Unknown ``name`` → 422.
         */
        get: operations["get_indicator_pairs__pair_id__indicators__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairs/{pair_id}/sr-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sr Candidates */
        get: operations["get_sr_candidates_pairs__pair_id__sr_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairs/{pair_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Pair
         * @description Fetch the most recent ``days`` worth of candles via the source adapter.
         */
        post: operations["refresh_pair_pairs__pair_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Charts */
        get: operations["list_charts_charts_get"];
        put?: never;
        /**
         * Create Chart
         * @description Create a new chart. 409 ``CHART_SLUG_CONFLICT`` if slug exists.
         */
        post: operations["create_chart_charts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chart */
        get: operations["get_chart_charts__slug__get"];
        /**
         * Update Chart
         * @description Edit-in-place. 404 ``CHART_NOT_FOUND`` if slug doesn't exist.
         */
        put: operations["update_chart_charts__slug__put"];
        post?: never;
        /** Delete Chart */
        delete: operations["delete_chart_charts__slug__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charts/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Chart
         * @description Multipart upload of a ``chart.json`` file.
         *
         *     Goes through ``chart_io.parse_chart_json`` so a ``schemaVersion``
         *     mismatch surfaces as ``SchemaVersionError`` (→ 422 SCHEMA_MISMATCH),
         *     not a generic ``ValidationError``.
         */
        post: operations["import_chart_charts_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charts/{slug}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Chart
         * @description Return the canonical ``chart.json`` payload (for download by the UI).
         */
        get: operations["export_chart_charts__slug__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairs/{pair_id}/ai_runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ai Runs */
        get: operations["list_ai_runs_pairs__pair_id__ai_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AIRun
         * @description Audit record for an AI-produced chart. Populated only on AI charts.
         */
        AIRun: {
            /** Model */
            model: string;
            /** Prompt Template Version */
            prompt_template_version: string;
            /** Context File Sha256 */
            context_file_sha256?: string | null;
            /** Context Preview */
            context_preview?: string | null;
            /** Sr Candidates Presented */
            sr_candidates_presented: components["schemas"]["SRCandidate"][];
            /** Sr Candidates Selected */
            sr_candidates_selected: string[];
        };
        /** AIRunResponse */
        AIRunResponse: {
            /** Run Id */
            run_id: number;
            /** Pair Id */
            pair_id: string;
            /** Chart Slug */
            chart_slug: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Prompt Template Version */
            prompt_template_version: string;
            /** Context File Sha256 */
            context_file_sha256?: string | null;
            /** Context Preview */
            context_preview?: string | null;
            /** Sr Candidates Selected */
            sr_candidates_selected: string[];
            /** Ran At */
            ran_at: number;
        };
        /**
         * Anchor
         * @description A single anchor on a drawing.
         *
         *     ``candidate_id`` is set on AI-created drawings to record which S/R
         *     candidate the model picked (the price is then resolved server-side).
         *     On user drawings ``candidate_id`` is ``None`` and ``price`` is whatever
         *     the user dragged the line to.
         */
        Anchor: {
            /** Ts Utc */
            ts_utc: number;
            /** Price */
            price: number;
            /** Candidate Id */
            candidate_id?: string | null;
        };
        /** Body_import_chart_charts_import_post */
        Body_import_chart_charts_import_post: {
            /** File */
            file: string;
        };
        /** CandleResponse */
        CandleResponse: {
            /** Ts Utc */
            ts_utc: number;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
        };
        /**
         * Chart
         * @description A complete chart artifact — ``schemaVersion: 1``.
         */
        Chart: {
            /**
             * Schemaversion
             * @default 1
             */
            schemaVersion: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Pair */
            pair: string;
            provenance: components["schemas"]["Provenance"];
            /** Parent Chart Id */
            parent_chart_id?: string | null;
            data: components["schemas"]["ChartData"];
            view: components["schemas"]["ChartView"];
            ai_run?: components["schemas"]["AIRun"] | null;
        };
        /**
         * ChartData
         * @description Default time-window the chart was authored against. Relative ('last
         *     N days from now'), not absolute, so charts stay evergreen.
         */
        ChartData: {
            /** Default Window Days */
            default_window_days: number;
            /**
             * Default Interval
             * @enum {string}
             */
            default_interval: "1h" | "1d" | "1w";
        };
        /** ChartListItemResponse */
        ChartListItemResponse: {
            /** Slug */
            slug: string;
            /** Pair Id */
            pair_id: string;
            /** Title */
            title: string;
            /**
             * Prov Kind
             * @enum {string}
             */
            prov_kind: "user" | "ai";
            /** Prov Model */
            prov_model?: string | null;
            /** Parent Chart Slug */
            parent_chart_slug?: string | null;
            /** Ai Run Id */
            ai_run_id?: number | null;
            /** Updated At Unix */
            updated_at_unix: number;
        };
        /** ChartView */
        ChartView: {
            /** Indicators */
            indicators?: components["schemas"]["Indicator"][];
            /** Drawings */
            drawings?: components["schemas"]["Drawing"][];
            /** Analysis Text */
            analysis_text?: string | null;
        };
        /** CreatePairRequest */
        CreatePairRequest: {
            /**
             * Pair Id
             * @description Canonical id, e.g. 'coinbase:BTC-USD'
             */
            pair_id: string;
        };
        /**
         * Drawing
         * @description A single drawing on a chart (trend line, horizontal, fib, rectangle).
         *
         *     ``provenance`` is **omitted** on user-created drawings (the chart-level
         *     provenance covers them). It is **required** on AI-created drawings so
         *     rationale and confidence travel with each individual line.
         */
        Drawing: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "trend" | "horizontal" | "fib" | "rect";
            /** Anchors */
            anchors: components["schemas"]["Anchor"][];
            style: components["schemas"]["Style"];
            provenance?: components["schemas"]["Provenance"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** Indicator */
        Indicator: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Params */
            params?: {
                [key: string]: number | string | boolean;
            };
            /**
             * Pane
             * @default 0
             */
            pane: number;
        };
        /** IndicatorPointResponse */
        IndicatorPointResponse: {
            /** Ts Utc */
            ts_utc: number;
            /** Value */
            value: number;
        };
        /** IndicatorResponse */
        IndicatorResponse: {
            /** Pair Id */
            pair_id: string;
            /** Interval */
            interval: string;
            /** Name */
            name: string;
            /** Params */
            params: {
                [key: string]: number | string | boolean;
            };
            /** Series */
            series: components["schemas"]["IndicatorSeriesResponse"][];
        };
        /**
         * IndicatorSeriesResponse
         * @description One named series. Multi-output indicators (MACD, BB) emit multiple.
         */
        IndicatorSeriesResponse: {
            /** Name */
            name: string;
            /** Output Key */
            output_key: string;
            /** Points */
            points: components["schemas"]["IndicatorPointResponse"][];
        };
        /** PairResponse */
        PairResponse: {
            /** Pair Id */
            pair_id: string;
            /** Base */
            base: string;
            /** Quote */
            quote: string;
            /** Source */
            source: string;
            /** Added At */
            added_at: number;
            /** Last Viewed At */
            last_viewed_at?: number | null;
            /** Is Pinned */
            is_pinned: boolean;
            /** Pinned Context Path */
            pinned_context_path?: string | null;
        };
        /**
         * Provenance
         * @description Who created this object and when. ``model`` is set only when
         *     ``kind == "ai"``. ``confidence`` and ``rationale`` are typically only
         *     set on AI-created drawings; on chart-level provenance they're omitted.
         */
        Provenance: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "user" | "ai";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Model */
            model?: string | null;
            /** Prompt Template Version */
            prompt_template_version?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Rationale */
            rationale?: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /**
             * Interval
             * @default 1d
             * @enum {string}
             */
            interval: "1h" | "1d";
            /**
             * Days
             * @default 30
             */
            days: number;
        };
        /** RefreshResponse */
        RefreshResponse: {
            /** Pair Id */
            pair_id: string;
            /** Interval */
            interval: string;
            /** Fetched */
            fetched: number;
        };
        /**
         * SRCandidate
         * @description One S/R candidate as presented to the LLM.
         *
         *     The full set is recorded in ``AIRun.sr_candidates_presented`` for audit
         *     so a future replay can know exactly what the model chose from.
         */
        SRCandidate: {
            /** Id */
            id: string;
            /** Price */
            price: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "support" | "resistance";
            /** Method */
            method: string;
            /** Touches */
            touches: number;
            /** Strength Score */
            strength_score: number;
            /** First Seen */
            first_seen: number;
            /** Last Touch */
            last_touch: number;
        };
        /** SRCandidateResponse */
        SRCandidateResponse: {
            /** Id */
            id: string;
            /** Price */
            price: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "support" | "resistance";
            /** Method */
            method: string;
            /** Touches */
            touches: number;
            /** Strength Score */
            strength_score: number;
            /** First Seen */
            first_seen: number;
            /** Last Touch */
            last_touch: number;
        };
        /** SRCandidatesResponse */
        SRCandidatesResponse: {
            /** Pair Id */
            pair_id: string;
            /** Interval */
            interval: string;
            /** Candidates */
            candidates: components["schemas"]["SRCandidateResponse"][];
        };
        /** Style */
        Style: {
            /** Color */
            color: string;
            /**
             * Dash
             * @default solid
             * @enum {string}
             */
            dash: "solid" | "dashed" | "dotted";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_pairs_pairs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"][];
                };
            };
        };
    };
    create_pair_pairs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePairRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_pair_pairs__pair_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pair_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candles_pairs__pair_id__candles_get: {
        parameters: {
            query?: {
                interval?: "1h" | "1d" | "1w";
                window_days?: number;
            };
            header?: never;
            path: {
                pair_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandleResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_indicator_pairs__pair_id__indicators__name__get: {
        parameters: {
            query?: {
                interval?: "1h" | "1d" | "1w";
                period?: number | null;
                fast?: number | null;
                slow?: number | null;
                signal?: number | null;
                stddev?: number | null;
            };
            header?: never;
            path: {
                pair_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sr_candidates_pairs__pair_id__sr_candidates_get: {
        parameters: {
            query?: {
                interval?: "1h" | "1d" | "1w";
                window_days?: number;
                top_n?: number;
            };
            header?: never;
            path: {
                pair_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SRCandidatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_pair_pairs__pair_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pair_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_charts_charts_get: {
        parameters: {
            query?: {
                pair_id?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartListItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_chart_charts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Chart"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chart"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chart_charts__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chart"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_chart_charts__slug__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Chart"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chart"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chart_charts__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_chart_charts_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_chart_charts_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chart"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_chart_charts__slug__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ai_runs_pairs__pair_id__ai_runs_get: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path: {
                pair_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIRunResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
